---
- name: Check if Swarm has already been Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  tags: swarm

- name: Initialize Docker Swarm
  shell: >
        docker swarm init        
        --advertise-addr={{ hostvars[inventory_hostname].cluster_host }}:2377
  when: swarm_status.rc != 0
  run_once: true
  tags: swarm