---
- name: Install Packages
  no_log: yes
  apt: 
    name:
      - acl
      - ntp
      - python
      - tcpdump
      - wget
      - openssl
      - curl
      - gnupg
      - apt-transport-https
      - ca-certificates
      - software-properties-common 
    state: present
    autoclean: yes