---
- name: Get the Manager join-token
  shell: docker swarm join-token --quiet manager
  register: manager_token
  tags: swarm

- name: Get the worker join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token
  tags: swarm