---
- name: Add Cluster IP address of all hosts to /etc/hosts file
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].cluster_host }} {{item}}"
    state: present
  when: hostvars[item].cluster_host is defined
  with_items: "{{ groups.all }}"